import { expect, test } from '@playwright/test'

test('opens the product-manager agent and sends workspace context through the unified API', async ({ page }) => {
  let capturedBody
  await page.route('**/api/agent/chat', async (route) => {
    if (route.request().method() === 'GET') return route.fulfill({ json: { configured: true, model: 'test-model' } })
    capturedBody = route.request().postDataJSON()
    await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ content: '当前窗口需要同时检查注意力与产品供给。', provider: 'test', model: 'test-model' }) })
  })
  await page.goto('/')
  await page.getByRole('button', { name: /简报助手\s*解释与追问/ }).click()
  const panel = page.getByRole('complementary', { name: '公募基金简报助手' })
  await expect(panel).toBeVisible()
  await expect(panel.getByText('已同步')).toBeVisible()
  const starterBox = await panel.getByRole('button', { name: '四象限怎么看？' }).boundingBox()
  expect(starterBox.height).toBeLessThan(50)
  await panel.getByRole('button', { name: '四象限怎么看？' }).click()
  await expect(panel.getByText('当前窗口需要同时检查注意力与产品供给。')).toBeVisible()
  await expect(panel.getByRole('link', { name: /注意力母池/ })).toBeVisible()
  expect(capturedBody.context.workspace).toBe('预研产品池')
  expect(capturedBody.context.workspaceData.coreDirections).toHaveLength(10)
  expect(capturedBody.context.pageKnowledge.quadrant.horizontalAxis).toContain('产业核心需求40%')
  expect(capturedBody.context.pageKnowledge.rankingRules.quarter).toContain('估算资金流35%')
  expect(capturedBody.context.workspaceData.horizonRankings.year.top10).toHaveLength(10)
  expect(capturedBody.context.pageContext.selectedTheme.name).toBeTruthy()
  expect(capturedBody.messages.at(-1).content).toBe('四象限怎么看？')
})

test('keeps the unified model configuration only in the browser session', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /简报助手\s*解释与追问/ }).click()
  const panel = page.getByRole('complementary', { name: '公募基金简报助手' })
  await panel.getByRole('button', { name: '模型设置' }).click()
  await expect(panel.getByLabel('服务商')).toHaveValue('zhipu')
  await expect(panel.getByLabel('API 地址')).toHaveValue('https://open.bigmodel.cn/api/paas/v4')
  await panel.getByLabel('API Key').fill('test-session-key')
  await panel.getByRole('button', { name: '保存并重新分析' }).click()
  const stored = await page.evaluate(() => JSON.parse(sessionStorage.getItem('ai-fund-mate-analysis-session-v1')))
  expect(stored).toMatchObject({ provider: 'zhipu', model: 'glm-5.2', apiKey: 'test-session-key' })
})

test('executes only a whitelisted read-only page action returned by the model', async ({ page }) => {
  await page.route('**/api/agent/chat', async (route) => {
    if (route.request().method() === 'GET') return route.fulfill({ json: { configured: true, model: 'test-model' } })
    return route.fulfill({ json: { content: '已经为你定位该方向。', actions: [{ name: 'focus_research_theme', label: '定位预研方向', arguments: { themeId: 'industrial-software' } }], sources: [{ label: '注意力母池', href: '/attention_pool_evidence.json' }] } })
  })
  await page.goto('/')
  await page.getByRole('button', { name: /简报助手\s*解释与追问/ }).click()
  const panel = page.getByRole('complementary', { name: '公募基金简报助手' })
  await expect(panel.getByText('已同步')).toBeVisible()
  await panel.getByPlaceholder('询问产品方向、趋势或数据依据…').fill('打开工业软件方向')
  await panel.getByRole('button', { name: '发送' }).click()
  await expect(panel.getByText(/已执行页面操作：定位预研方向/)).toBeVisible()
  await expect(page.getByRole('main', { name: '工业软件与自主生产系统方向详情' }).getByRole('heading', { name: '工业软件与自主生产系统' })).toBeVisible()
})

test('aborts an in-flight request when the conversation is cleared', async ({ page }) => {
  await page.route('**/api/agent/chat', async (route) => {
    if (route.request().method() === 'GET') return route.fulfill({ json: { configured: true, model: 'test-model' } })
    await new Promise((resolve) => setTimeout(resolve, 5_000))
    return route.fulfill({ json: { content: '不应出现' } }).catch(() => {})
  })
  await page.goto('/')
  await page.getByRole('button', { name: /简报助手\s*解释与追问/ }).click()
  const panel = page.getByRole('complementary', { name: '公募基金简报助手' })
  await expect(panel.getByText('已同步')).toBeVisible()
  await panel.getByRole('button', { name: '四象限怎么看？' }).click()
  await expect(panel.getByText('正在分析…')).toBeVisible()
  await panel.getByRole('button', { name: '清空对话' }).click()
  await expect(panel.getByText('正在分析…')).toHaveCount(0)
  await expect(panel.getByText('我是简报助手。')).toBeVisible()
})
