import { test, expect } from '@playwright/test'

test('shows public-data evidence and drills into product supply', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '预研产品池', exact: true }).click()
  await expect(page.getByRole('heading', { name: '季度预研产品池' })).toBeVisible()
  await expect(page.locator('.attention-proof').first()).toContainText('百度热搜 × 头条热榜')
  await expect(page.locator('.attention-detail').getByText('综合社会注意力', { exact: true })).toBeVisible()
  await expect(page.locator('.attention-head')).toContainText('Wikimedia长期认知20%')
  await expect(page.locator('.attention-wiki-score')).toContainText('短中期注意力 · 80%')
  await expect(page.locator('.attention-wiki-score')).toContainText('长期公众认知 · 20%')
  await expect(page.locator('.attention-legend > span')).toHaveCount(5)
  for (const label of ['注意力领先区','需求—注意力共振区','潜在方向观察区','提前预研区','未破圈观察带']) {
    await expect(page.getByText(label,{exact:false}).first()).toBeVisible()
  }
  await page.getByLabel('显示名称',{exact:true}).check()
  const clippedLabels = await page.locator('.attention-canvas').evaluate((canvas) => {
    const bounds=canvas.getBoundingClientRect()
    return [...canvas.querySelectorAll('.attention-dot.is-active span')].filter((label)=>{const box=label.getBoundingClientRect();return box.left<bounds.left||box.right>bounds.right||box.top<bounds.top||box.bottom>bounds.bottom}).length
  })
  expect(clippedLabels).toBe(0)
  await page.locator('.attention-detail').getByText('社会注意力', { exact: true }).click()
  await expect(page.locator('.attention-detail').getByText('近30日上榜次数', { exact: true })).toBeVisible()
  await page.locator('.attention-detail').getByText('同类基金市场表现', { exact: true }).click()
  await expect(page.locator('.attention-detail').getByText('估算资金净增', { exact: true })).toBeVisible()
  await expect(page.locator('.attention-detail').getByText('规模增长产品占比', { exact: true })).toBeVisible()
  const brief = page.getByRole('region', { name: '前瞻产品方向简报' })
  await expect(brief).toBeVisible()
  await expect(page.getByText('母池准入标准')).toHaveCount(0)
  await expect(brief.getByRole('button', { name: '未来1个月' })).toHaveCount(0)
  await expect(brief.getByText('产品市场验证', { exact: true })).toHaveCount(0)
  await brief.getByRole('button', { name: '未来3个月' }).click()
  await expect(brief.getByText('季度关注').first()).toBeVisible()
  await brief.getByRole('button', { name: '未来半年' }).click()
  await expect(brief.getByText('半年关注').first()).toBeVisible()
  await brief.getByRole('button', { name: '未来1年' }).click()
  await expect(brief.getByText('年度关注').first()).toBeVisible()
  const briefDirection = await brief.locator('.horizon-analysis > div > strong').textContent()
  await brief.getByRole('button', { name: /查看该方向完整判断/ }).click()
  await expect(page.locator('.decision-detail')).toContainText(briefDirection)
  await expect(page.getByText('产品方向可行性')).toBeVisible()
  const cockpit = page.getByRole('region', { name: '主题趋势与假设验证' })
  await expect(cockpit).toBeVisible()
  await expect(cockpit.locator('.theme-trend-legend')).toContainText('社会注意力')
  await expect(cockpit.locator('.theme-trend-legend')).toContainText('龙头收入')
  await expect(cockpit.locator('.theme-trend-legend')).toContainText('板块价格')
  await expect(cockpit.locator('.theme-trend-legend')).toContainText('同类规模')
  await cockpit.getByRole('button', { name: '近半年' }).click()
  await expect(cockpit.getByRole('button', { name: '近半年' })).toHaveClass(/active/)
  await expect(cockpit.getByText('本期排序依据', { exact: true })).toHaveCount(0)
  await expect(cockpit.getByText(/核心假设/)).toHaveCount(0)
  await expect(cockpit.getByText('自动证伪条件', { exact: true })).toHaveCount(0)
  await expect(cockpit.getByText(/长期公众认知 · Wikimedia/)).toBeVisible()
  await expect(cockpit.getByText(/词条篮子：/)).toBeVisible()
  await expect(cockpit.getByText(/ETF真实需求/)).toHaveCount(0)
  const evidence = page.locator('.decision-detail')
  await expect(evidence.getByText('产业需求是否成立', { exact: true })).toBeVisible()
  await expect(evidence.getByText('龙头企业是否兑现', { exact: true })).toBeVisible()
  await expect(evidence.getByText('资产池能否支撑产品', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /龙头企业是否兑现/ }).click()
  await expect(page.getByRole('heading', { name: '龙头企业是否兑现' })).toBeVisible()
  await expect(page.getByText('10家公司收入增速中位数', { exact: true })).toBeVisible()
  await expect(page.getByText('当前判断', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: /资产池能否支撑产品/ }).click()
  await expect(page.getByText('前十大占比', { exact: true })).toBeVisible()
  await expect(page.getByText('集中度 HHI', { exact: true })).toBeVisible()
  await expect(page.getByText(/前十大成分股 · 合计/)).toBeVisible()
  await expect(page.locator('.top-constituents > div > div')).toHaveCount(11)
  await page.getByLabel('资产池能否支撑产品').getByRole('button', { name: '近3个月', exact: true }).click()
  await expect(page.locator('.asset-history nav button.active')).toHaveText('近3个月')
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.locator('.decision-detail').getByRole('button', { name: /同类基金/ }).click()
  await expect(page.getByRole('heading', { name: '全部同类基金' })).toBeVisible()
  const table = page.locator('.peer-table')
  const columnValues = async (column) => table.locator(':scope > div').evaluateAll((rows, index) => rows.slice(1).map((row) => Number.parseFloat(row.children[index].textContent)).filter(Number.isFinite), column)
  const isDescending = (values) => values.every((value, index) => index === 0 || values[index - 1] >= value)
  await expect.poll(async () => isDescending(await columnValues(3))).toBe(true)
  await page.getByLabel('同类基金排序').selectOption('growth')
  await expect.poll(async () => isDescending(await columnValues(5))).toBe(true)
})
