import { test, expect } from '@playwright/test'

test('shows public-data evidence and drills into product supply', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '预研产品池', exact: true }).click()
  await expect(page.getByRole('heading', { name: '核心预研产品池' })).toBeVisible()
  await expect(page.locator('.attention-proof').first()).toContainText('百度热搜 × 头条热榜')
  await expect(page.locator('.attention-detail').getByText('综合关注与认知', { exact: true })).toBeVisible()
  await expect(page.locator('.attention-head')).toContainText('产业核心需求40%')
  await expect(page.locator('.attention-wiki-score')).toContainText('国内短中期基础信号')
  await expect(page.locator('.attention-wiki-score')).toContainText('长期公众认知信号')
  await expect(page.locator('.attention-legend > span')).toHaveCount(5)
  for (const label of ['关注领先区','机会—关注共振区','潜在方向观察区','提前预研区','未破圈观察带']) {
    await expect(page.getByText(label,{exact:false}).first()).toBeVisible()
  }
  await page.getByLabel('显示名称',{exact:true}).check()
  const clippedLabels = await page.locator('.attention-canvas').evaluate((canvas) => {
    const bounds=canvas.getBoundingClientRect()
    return [...canvas.querySelectorAll('.attention-dot.is-active span')].filter((label)=>{const box=label.getBoundingClientRect();return box.left<bounds.left||box.right>bounds.right||box.top<bounds.top||box.bottom>bounds.bottom}).length
  })
  expect(clippedLabels).toBe(0)
  await page.locator('.attention-detail').getByText('社会注意力', { exact: true }).click()
  await expect(page.locator('.attention-detail').getByText('近30日上榜次数', { exact: true })).toBeVisible()
  await page.locator('.attention-detail').getByText('同类基金市场表现', { exact: true }).click()
  await expect(page.locator('.attention-detail').getByText('估算资金净增', { exact: true })).toBeVisible()
  await expect(page.locator('.attention-detail').getByText('规模增长产品占比', { exact: true })).toBeVisible()
  const brief = page.getByRole('region', { name: '产品池期限决策简报' })
  await expect(brief).toBeVisible()
  await expect(page.getByText('母池准入标准')).toHaveCount(0)
  await expect(brief.getByRole('button', { name: '未来1个月' })).toHaveCount(0)
  await expect(brief.getByText('产品市场验证', { exact: true })).toHaveCount(0)
  await brief.getByRole('button', { name: '未来3个月' }).click()
  await expect(brief.getByText('未来3个月 · 产品池整体判断').first()).toBeVisible()
  const quarterNames = await brief.locator('.horizon-list strong').allTextContents()
  await brief.getByRole('button', { name: '未来半年' }).click()
  await expect(brief.getByText('未来半年 · 产品池整体判断').first()).toBeVisible()
  const halfYearNames = await brief.locator('.horizon-list strong').allTextContents()
  await brief.getByRole('button', { name: '未来1年' }).click()
  await expect(brief.getByText('未来1年 · 产品池整体判断').first()).toBeVisible()
  const yearNames = await brief.locator('.horizon-list strong').allTextContents()
  expect(new Set([quarterNames.join('|'), halfYearNames.join('|'), yearNames.join('|')]).size).toBeGreaterThan(1)
  const directionButton = brief.locator('.horizon-list > button').first()
  const briefDirection = await directionButton.locator('strong').textContent()
  await directionButton.click()
  const themePage = page.getByRole('main', { name: `${briefDirection}方向详情` })
  await expect(themePage).toBeVisible()
  await expect(page).toHaveURL(/theme=/)
  await expect(themePage.getByRole('heading', { name: briefDirection })).toBeVisible()
  await expect(themePage.getByRole('heading', { name: '产品方向可行性' })).toBeVisible()
  const cockpit = themePage.getByRole('region', { name: '主题趋势与假设验证' })
  await expect(cockpit).toBeVisible()
  await expect(cockpit.locator('.theme-trend-legend')).toContainText('社会注意力')
  await expect(cockpit.locator('.theme-trend-legend')).toContainText('龙头收入')
  await expect(cockpit.locator('.theme-trend-legend')).toContainText('板块价格')
  await expect(cockpit.locator('.theme-trend-legend')).toContainText('同类规模')
  await cockpit.getByRole('button', { name: '近半年' }).click()
  await expect(cockpit.getByRole('button', { name: '近半年' })).toHaveClass(/active/)
  await expect(cockpit.getByText('本期排序依据', { exact: true })).toHaveCount(0)
  await expect(cockpit.getByText(/核心假设/)).toHaveCount(0)
  await expect(cockpit.getByText('自动证伪条件', { exact: true })).toHaveCount(0)
  await expect(cockpit.getByText(/长期公众认知 · Wikimedia/)).toBeVisible()
  await expect(cockpit.getByText(/词条篮子：/)).toBeVisible()
  await expect(cockpit.getByText(/ETF真实需求/)).toHaveCount(0)
  const evidence = themePage
  await expect(evidence.getByText('产业核心需求', { exact: true })).toBeVisible()
  await expect(evidence.getByText('龙头企业是否兑现', { exact: true })).toBeVisible()
  await expect(evidence.getByText('资产池能否支撑产品', { exact: true })).toBeVisible()
  await themePage.getByRole('button', { name: /龙头企业是否兑现/ }).click()
  await expect(page.getByRole('heading', { name: '龙头企业是否兑现' })).toBeVisible()
  await expect(page.getByText('10家公司收入增速中位数', { exact: true })).toBeVisible()
  await expect(page.getByText('当前判断', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await themePage.getByRole('button', { name: /资产池能否支撑产品/ }).click()
  await expect(page.getByText('前十大占比', { exact: true })).toBeVisible()
  await expect(page.getByText('集中度 HHI', { exact: true })).toBeVisible()
  await expect(page.getByText(/前十大成分股 · 合计/)).toBeVisible()
  await expect(page.locator('.top-constituents > div > div')).toHaveCount(11)
  await page.getByLabel('资产池能否支撑产品').getByRole('button', { name: '近3个月', exact: true }).click()
  await expect(page.locator('.asset-history nav button.active')).toHaveText('近3个月')
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await themePage.getByRole('button', { name: /同类基金/ }).click()
  await expect(page.getByRole('heading', { name: '全部同类基金' })).toBeVisible()
  const table = page.locator('.peer-table')
  const columnValues = async (column) => table.locator(':scope > div').evaluateAll((rows, index) => rows.slice(1).map((row) => Number.parseFloat(row.children[index].textContent)).filter(Number.isFinite), column)
  const isDescending = (values) => values.every((value, index) => index === 0 || values[index - 1] >= value)
  await expect.poll(async () => isDescending(await columnValues(3))).toBe(true)
  await page.getByLabel('同类基金排序').selectOption('growth')
  await expect.poll(async () => isDescending(await columnValues(5))).toBe(true)
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await themePage.getByRole('button', { name: '← 返回预研产品池' }).click()
  await expect(page).not.toHaveURL(/theme=/)
})

test('supports the interactive horizon brief without the retired product-window panel', async ({ page }) => {
  await page.goto('/')
  const brief = page.getByRole('region', { name: '产品池期限决策简报' })
  await expect(brief.getByRole('heading', { name: '产品经理前瞻简报' })).toBeVisible()
  await expect(brief.locator('.horizon-list > button')).toHaveCount(10)
  await expect(brief.locator('.rank-move')).toHaveCount(10)
  await expect(page.getByRole('region', { name: '产品窗口与预警' })).toHaveCount(0)
  await brief.getByRole('button', { name: '规模净增最快' }).click()
  await expect(brief.getByText('规模净增最快 · 数据说明')).toBeVisible()
  await brief.getByRole('button', { name: '查看证据链' }).click()
  await expect(brief.getByText('本期证据链', { exact: true })).toBeVisible()
  await brief.getByRole('button', { name: '历史对比' }).click()
  await expect(brief.getByText('历史对比', { exact: true }).last()).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await brief.getByRole('button', { name: '导出本期简报' }).click()
  const stream = await (await downloadPromise).createReadStream()
  let exported = ''
  for await (const chunk of stream) exported += chunk.toString('utf8')
  expect(exported).toContain('规模净增最快：')
  expect(exported).toContain('Top 10 本期变化：')
  expect(exported).not.toContain('undefined')
})
