"""Wait until the production deployment serves the snapshot generated by this run."""

from __future__ import annotations

import argparse
import json
import time
from datetime import datetime
from urllib.parse import urljoin
from urllib.request import Request, urlopen


def _json(url: str) -> dict:
    request = Request(f"{url}?verify={int(time.time())}", headers={"Cache-Control": "no-cache"})
    with urlopen(request, timeout=20) as response:
        return json.load(response)


def _date(value: object) -> str | None:
    if not isinstance(value, str):
        return None
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00")).date().isoformat()
    except ValueError:
        return value[:10] if len(value) >= 10 else None


def wait_for_deployment(base_url: str, expected_date: str, timeout_seconds: int) -> None:
    deadline = time.monotonic() + timeout_seconds
    last_observed: dict[str, str | None] = {}
    while time.monotonic() < deadline:
        try:
            products = _json(urljoin(base_url.rstrip("/") + "/", "fund_products.json"))
            issuance = _json(urljoin(base_url.rstrip("/") + "/", "issuance_insights.json"))
            attention = _json(urljoin(base_url.rstrip("/") + "/", "attention_pool_evidence.json"))
            status = _json(urljoin(base_url.rstrip("/") + "/", "data_status.json"))
            last_observed = {
                "fund_products": _date(products.get("updateTime")),
                "issuance_insights": _date(issuance.get("dataDate")),
                "attention_pool": _date(attention.get("generatedAt")),
                "data_status": _date(status.get("snapshotDate")),
            }
            attention_complete = attention.get("verifiedCount") == 36 and len(attention.get("recommendedIds") or []) == 10
            if all(value == expected_date for value in last_observed.values()) and attention_complete:
                print(f"Production snapshots are current: {last_observed}")
                return
        except (OSError, ValueError, json.JSONDecodeError) as error:
            last_observed = {"error": str(error)}
        time.sleep(15)
    raise TimeoutError(f"production did not publish {expected_date} within {timeout_seconds}s; last={last_observed}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base-url", required=True)
    parser.add_argument("--expected-date", required=True)
    parser.add_argument("--timeout-seconds", type=int, default=600)
    args = parser.parse_args()
    wait_for_deployment(args.base_url, args.expected_date, args.timeout_seconds)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
