"""Wait until the production deployment serves the snapshot generated by this run."""

from __future__ import annotations

import argparse
import json
import time
from datetime import datetime, timedelta, timezone
from urllib.parse import urljoin
from urllib.request import Request, urlopen


def _json(url: str) -> dict:
    request = Request(f"{url}?verify={int(time.time())}", headers={"Cache-Control": "no-cache"})
    with urlopen(request, timeout=20) as response:
        return json.load(response)


def _date(value: object) -> str | None:
    if not isinstance(value, str):
        return None
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00")).date().isoformat()
    except ValueError:
        return value[:10] if len(value) >= 10 else None


def _timestamp(value: object) -> datetime | None:
    if not isinstance(value, str):
        return None
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def _attention_is_fresh(value: object, max_age_hours: float, now: datetime | None = None) -> bool:
    generated_at = _timestamp(value)
    if generated_at is None:
        return False
    reference = now or datetime.now(timezone.utc)
    if reference.tzinfo is None:
        reference = reference.replace(tzinfo=timezone.utc)
    age = reference.astimezone(timezone.utc) - generated_at
    return timedelta(minutes=-15) <= age <= timedelta(hours=max_age_hours)


def wait_for_deployment(
    base_url: str,
    expected_date: str,
    timeout_seconds: int,
    attention_max_age_hours: float = 4,
) -> None:
    deadline = time.monotonic() + timeout_seconds
    last_observed: dict[str, str | None] = {}
    while time.monotonic() < deadline:
        try:
            products = _json(urljoin(base_url.rstrip("/") + "/", "fund_products.json"))
            issuance = _json(urljoin(base_url.rstrip("/") + "/", "issuance_insights.json"))
            attention = _json(urljoin(base_url.rstrip("/") + "/", "attention_pool_evidence.json"))
            status = _json(urljoin(base_url.rstrip("/") + "/", "data_status.json"))
            last_observed = {
                "fund_products": _date(products.get("updateTime")),
                "issuance_insights": _date(issuance.get("dataDate")),
                "data_status": _date(status.get("snapshotDate")),
                "attention_generated_at": attention.get("generatedAt"),
            }
            attention_complete = attention.get("verifiedCount") == 36 and len(attention.get("recommendedIds") or []) == 10
            daily_snapshots_match = all(
                last_observed[key] == expected_date
                for key in ("fund_products", "issuance_insights", "data_status")
            )
            attention_fresh = _attention_is_fresh(attention.get("generatedAt"), attention_max_age_hours)
            if daily_snapshots_match and attention_complete and attention_fresh:
                print(f"Production snapshots are current: {last_observed}")
                return
        except (OSError, ValueError, json.JSONDecodeError) as error:
            last_observed = {"error": str(error)}
        time.sleep(15)
    raise TimeoutError(f"production did not publish {expected_date} within {timeout_seconds}s; last={last_observed}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base-url", required=True)
    parser.add_argument("--expected-date", required=True)
    parser.add_argument("--timeout-seconds", type=int, default=600)
    parser.add_argument("--attention-max-age-hours", type=float, default=4)
    args = parser.parse_args()
    wait_for_deployment(
        args.base_url,
        args.expected_date,
        args.timeout_seconds,
        args.attention_max_age_hours,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
