begin;

do $$
begin
    if not exists (select 1 from pg_roles where rolname = 'signal_pipeline_writer') then
        create role signal_pipeline_writer nologin;
    end if;
end
$$;

create table public.sources (
    id text primary key,
    name text not null,
    url text not null,
    source_tier text not null check (source_tier in ('official', 'self_regulatory', 'industry', 'media')),
    enabled boolean not null default true,
    description text not null default '',
    official boolean not null default false,
    base_weight double precision not null default 0 check (base_weight between 0 and 1),
    collector text not null default '',
    categories jsonb not null default '[]'::jsonb,
    region text not null default '',
    access_notes text not null default ''
);

create table public.raw_items (
    id bigint generated by default as identity primary key,
    source_id text not null references public.sources(id),
    url text not null,
    title text not null,
    content text not null default '',
    body text,
    content_hash text not null unique,
    collected_at timestamptz not null,
    published_at timestamptz,
    metadata jsonb not null default '{}'::jsonb,
    content_status text not null default 'available'
);

create table public.event_clusters (
    id text primary key,
    title text not null,
    category text not null,
    summary text not null default '',
    created_at timestamptz not null,
    updated_at timestamptz not null,
    topic_key text not null default '',
    item_count integer not null default 0 check (item_count >= 0),
    independent_source_count integer not null default 0 check (independent_source_count >= 0)
);

create table public.signals (
    id text primary key,
    cluster_id text references public.event_clusters(id),
    category text not null,
    title text not null,
    summary text not null default '',
    priority integer not null,
    source_confidence double precision not null check (source_confidence between 0 and 1),
    customer_demand_score double precision not null check (customer_demand_score between 0 and 1),
    demand_kind text not null check (demand_kind in ('direct', 'proxy', 'media_attention', 'unknown')),
    validation_status text not null check (validation_status in ('pending_official_validation', 'confirmed', 'rejected')),
    published_at timestamptz,
    created_at timestamptz not null,
    updated_at timestamptz not null
);

create table public.signal_evidence (
    id bigint generated by default as identity primary key,
    signal_id text not null references public.signals(id) on delete cascade,
    raw_item_id bigint not null references public.raw_items(id) on delete cascade,
    evidence_type text not null,
    excerpt text not null default '',
    source_confidence double precision not null check (source_confidence between 0 and 1),
    unique (signal_id, raw_item_id, evidence_type)
);

create table public.catalysts (
    id text primary key,
    signal_id text references public.signals(id) on delete set null,
    title text not null,
    scheduled_at timestamptz not null,
    priority integer not null,
    description text not null default '',
    validation_status text not null check (validation_status in ('pending_official_validation', 'confirmed', 'rejected'))
);

create table public.daily_briefs (
    id text primary key,
    window_start timestamptz not null,
    window_end timestamptz not null,
    generated_at timestamptz not null,
    body text not null,
    status text not null default 'published',
    signal_ids jsonb not null default '[]'::jsonb,
    top_call text not null default '',
    check (window_start < window_end)
);

create table public.pipeline_runs (
    id text primary key,
    command text not null,
    started_at timestamptz not null,
    finished_at timestamptz,
    status text not null,
    summary text not null default ''
);

create index raw_items_published_at_idx on public.raw_items (published_at);
create index signals_category_priority_idx on public.signals (category, priority desc);
create index signals_cluster_id_idx on public.signals (cluster_id);
create index catalysts_scheduled_at_idx on public.catalysts (scheduled_at);

alter table public.sources enable row level security;
alter table public.raw_items enable row level security;
alter table public.event_clusters enable row level security;
alter table public.signals enable row level security;
alter table public.signal_evidence enable row level security;
alter table public.catalysts enable row level security;
alter table public.daily_briefs enable row level security;
alter table public.pipeline_runs enable row level security;

-- Base tables contain collection internals. No anon/authenticated policies are
-- created, so RLS denies every direct read and write. Server-side service-role
-- and direct PostgreSQL jobs retain their normal privileged access.
revoke all on table public.sources, public.raw_items, public.event_clusters,
    public.signals, public.signal_evidence, public.catalysts,
    public.daily_briefs, public.pipeline_runs from anon, authenticated;
revoke all on sequence public.raw_items_id_seq,
    public.signal_evidence_id_seq from anon, authenticated;

grant usage on schema public to signal_pipeline_writer;
grant select, insert, update, delete on table public.sources, public.raw_items,
    public.event_clusters, public.signals, public.signal_evidence, public.catalysts,
    public.daily_briefs, public.pipeline_runs to signal_pipeline_writer;
grant usage, select on sequence public.raw_items_id_seq,
    public.signal_evidence_id_seq to signal_pipeline_writer;

create policy sources_pipeline_access on public.sources for all to signal_pipeline_writer using (true) with check (true);
create policy raw_items_pipeline_access on public.raw_items for all to signal_pipeline_writer using (true) with check (true);
create policy event_clusters_pipeline_access on public.event_clusters for all to signal_pipeline_writer using (true) with check (true);
create policy signals_pipeline_access on public.signals for all to signal_pipeline_writer using (true) with check (true);
create policy signal_evidence_pipeline_access on public.signal_evidence for all to signal_pipeline_writer using (true) with check (true);
create policy catalysts_pipeline_access on public.catalysts for all to signal_pipeline_writer using (true) with check (true);
create policy daily_briefs_pipeline_access on public.daily_briefs for all to signal_pipeline_writer using (true) with check (true);
create policy pipeline_runs_pipeline_access on public.pipeline_runs for all to signal_pipeline_writer using (true) with check (true);

-- These owner-executed, read-only views are the complete browser surface.
-- Their predicates exclude unpublished drafts, while base-table grants remain
-- revoked. No view exposes database URLs, credentials, raw bodies, or run logs.
create view public.published_signals
with (security_barrier = true)
as
select
    s.id, s.cluster_id, s.category, s.title, s.summary, s.priority,
    s.source_confidence, s.customer_demand_score, s.demand_kind,
    s.validation_status, s.published_at, s.updated_at,
    coalesce(jsonb_agg(distinct jsonb_build_object(
        'url', r.url,
        'excerpt', e.excerpt,
        'confidence', e.source_confidence
    )) filter (where r.id is not null), '[]'::jsonb) as sources
from public.signals s
left join public.signal_evidence e on e.signal_id = s.id
left join public.raw_items r on r.id = e.raw_item_id
where s.published_at is not null
group by s.id;

create view public.published_catalysts
with (security_barrier = true)
as
select id, signal_id, title, scheduled_at, priority, description, validation_status
from public.catalysts;

create view public.published_daily_briefs
with (security_barrier = true)
as
select id, window_start, window_end, generated_at, body, status, signal_ids, top_call
from public.daily_briefs
where status = 'published';

revoke all on table public.published_signals, public.published_catalysts,
    public.published_daily_briefs from public;
grant select on table public.published_signals, public.published_catalysts,
    public.published_daily_briefs to anon, authenticated;

commit;
